# Utiliser une image Node.js officielle comme image de base  
FROM node:18  

# Définir le répertoire de travail à l'intérieur du conteneur  
WORKDIR /usr/src/app  

# Copier les fichiers package.json et package-lock.json dans le conteneur  
COPY package*.json ./  

# Installer les dépendances du projet  
RUN npm install  

# Copier le reste du code de l'application dans le conteneur  
COPY . .  

# Exposer le port sur lequel l'application écoute  
EXPOSE 5000  

# Commande pour démarrer l'application  
CMD ["node", "server.js"]  