version: "3.8"
services:
  phone-accessoire-catalog:
    build: .
    image: phone-accessoire-catalog:latest
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
